Revert "Add needed dependency for LayoutImportExportHelper migra..."
Revert submission 38922045-migrate-layout-export

Reason for revert: Build possibly broke becuse of the added dependency
Error: https://android-build.googleplex.com/builds/submitted/15041136/test_suites_arm64-trunk_staging/latest/logs/build_error.log?referrer=crowsnest

Reverted changes: /q/submissionid:38922045-migrate-layout-export

Bug: 491012579
Change-Id: Ia2d320ef35aa0f3c4389bf7b84a60be324d1b735